[package]
name = "dsl"
version = "0.1.0"
edition = "2021"

[dependencies]
serde.workspace = true
thiserror.workspace = true
log.workspace = true
vm-core = { path = "../vm-core" }
crypto = { path = "../crypto" }
