[package]
name = "crypto"
version = "0.1.0"
edition = "2021"

[dependencies]
serde.workspace = true
thiserror.workspace = true
log.workspace = true
sha2 = "0.10"
md-5 = "0.7"
aes-gcm = "0.10"
aead = "0.5"
rsa = "0.9"
rand = "0.8"
x509-cert = "0.2"
